USE RunData;

CREATE TABLE ClimbingToday (
	id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    writer VARCHAR(20) NOT NULL UNIQUE,
    inserted DATETIME DEFAULT NOW()
);

SELECT * FROM ClimbingToday;

DESC ClimbingToday;

ALTER TABLE ClimbingToday
MODIFY inserted DATETIME NOT NULL DEFAULT NOW();

